import { appSchema, tableSchema } from "@nozbe/watermelondb";

export default appSchema({
  version: 5,
  tables: [
    tableSchema({
      name: "events",
      columns: [
        { name: "sequence", type: "number" },
        { name: "entity", type: "string" },
        { name: "entity_id", type: "string" },
        { name: "type", type: "string" },
        { name: "payload_json", type: "string" },
        { name: "device_id", type: "string" },
        { name: "relay_id", type: "string" },
        { name: "user_id", type: "string" },
        { name: "venue_id", type: "string" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
        { name: "applied_at", type: "number", isOptional: true },
        { name: "lamport_clock", type: "number" },
        { name: "status", type: "string" },
        { name: "error_message", type: "string", isOptional: true },
        { name: "acked_at", type: "number", isOptional: true },
        { name: "outbox_id", type: "string", isIndexed: true },
      ],
    }),
    tableSchema({
      name: "orders",
      columns: [
        { name: "status", type: "string", isIndexed: true },
        { name: "table_id", type: "string", isOptional: true, isIndexed: true },
        { name: "guest_id", type: "string", isOptional: true },
        {
          name: "reservation_id",
          type: "string",
          isOptional: true,
          isIndexed: true,
        },
        { name: "items_json", type: "string" },
        { name: "opened_at", type: "number" },
        { name: "closed_at", type: "number", isOptional: true },
        { name: "voided_at", type: "number", isOptional: true },
        { name: "subtotal_cents", type: "number" },
        { name: "discount_cents", type: "number" },
        { name: "tax_cents", type: "number" },
        { name: "tronc_cents", type: "number" },
        { name: "total_cents", type: "number" },
        { name: "created_by_event_id", type: "string", isIndexed: true },
        { name: "updated_by_event_id", type: "string", isIndexed: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "outbox",
      columns: [
        { name: "date", type: "string", isIndexed: true },
        { name: "status", type: "string", isIndexed: true },
        { name: "synced_at", type: "number", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
  ],
});
